//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProjrct.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RajVamja_webapiEntities : DbContext
    {
        public RajVamja_webapiEntities()
            : base("name=RajVamja_webapiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<student> students { get; set; }
    
        public virtual ObjectResult<SP_StudentsDet_Result> SP_StudentsDet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_StudentsDet_Result>("SP_StudentsDet");
        }
    }
}
