//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagement_343.Models.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RajVamja_schoolmanagement_343Entities : DbContext
    {
        public RajVamja_schoolmanagement_343Entities()
            : base("name=RajVamja_schoolmanagement_343Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<student> students { get; set; }
    
        public virtual ObjectResult<SP_subjectList_Result> SP_subjectList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_subjectList_Result>("SP_subjectList");
        }
    
        public virtual ObjectResult<SP_stateList_Result2> SP_stateList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_stateList_Result2>("SP_stateList");
        }
    
        public virtual ObjectResult<SP_cityList_Result3> SP_cityList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_cityList_Result3>("SP_cityList");
        }
    
        public virtual int sp_DeleteCity(Nullable<int> cityId)
        {
            var cityIdParameter = cityId.HasValue ?
                new ObjectParameter("cityId", cityId) :
                new ObjectParameter("cityId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteCity", cityIdParameter);
        }
    
        public virtual int sp_DeleteCountry(Nullable<int> countryId)
        {
            var countryIdParameter = countryId.HasValue ?
                new ObjectParameter("countryId", countryId) :
                new ObjectParameter("countryId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteCountry", countryIdParameter);
        }
    
        public virtual int sp_DeleteState(Nullable<int> stateId)
        {
            var stateIdParameter = stateId.HasValue ?
                new ObjectParameter("stateId", stateId) :
                new ObjectParameter("stateId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteState", stateIdParameter);
        }
    
        public virtual int sp_DeleteStudent(Nullable<int> stdId)
        {
            var stdIdParameter = stdId.HasValue ?
                new ObjectParameter("stdId", stdId) :
                new ObjectParameter("stdId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeleteStudent", stdIdParameter);
        }
    
        public virtual ObjectResult<SP_studentsDetail_Result1> SP_studentsDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_studentsDetail_Result1>("SP_studentsDetail");
        }
    
        public virtual ObjectResult<SP_teachersDetail_Result1> SP_teachersDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_teachersDetail_Result1>("SP_teachersDetail");
        }
    }
}
